engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
  paths:
  - src/**
exclude_paths:
- lib/*
- "**.test.js"
